---
- name: Crear grupos necesarios
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - G_R1
    - G_R2
    - G_R3
    - G_R4
    - G_R5
    - G_R6
    - Grupo_001

- name: Crear usuarios
  user:
    name: "{{ item.nombre }}"
    groups: "G_R{{ item.rol }},Grupo_001"
    password: "{{ 'vagrant' | password_hash('sha512') }}"
  loop:
    - { nombre: "user1", rol: 1 }
    - { nombre: "user2", rol: 2 }
    - { nombre: "user3", rol: 3 }
    - { nombre: "user4", rol: 4 }
    - { nombre: "user5", rol: 5 }
    - { nombre: "user6", rol: 6 }

