---
# tasks file for TP_INI

# mensaje inicial
- name: "Rol: TP_INI - Grupo: {{ Nombre_Grupo }}"
  debug:
    msg: "Inicio de tareas dentro del Rol: TP_INI"

# creaci贸n de variables locales
- name: Definir variables locales
  set_fact:
    FECHA: "{{ ansible_date_time.date }}"
    DISTRIBUCION: "{{ ansible_distribution }}"
    CORES: "{{ ansible_processor_cores }}"

# creaci贸n del directorio
- name: Crear el directorio /tmp/Grupo
  file:
    path: /tmp/Grupo
    state: directory
    owner: vagrant
    mode: '0755'
                   
# carga del archivo
- name: Crear el archivo datos.txt y su directorio
  copy:
    dest: /tmp/Grupo/datos.txt
    content: |
      Nombre Grupo: {{ Nombre_Grupo }}
      Divisi贸n: {{ Division }}
      Fecha: {{ FECHA }}
      -------------------------
      Distribuci贸n: {{ DISTRIBUCION }}
      Cantidad de Cores: {{ CORES }}
      -------------------------
      {% for key, usuario in Usuarios.items() -%}
      {{ key }}: Nombre: {{ usuario.nombre }} Apellido: {{ usuario.apellido }}
      {% endfor %}
    owner: vagrant
    mode: '0644'
